### ISSUE TITLE
Update query to exclude regressions that relman has decided not to track

### ISSUE THREAD

**Issue by lizzard** [mozilla/releasehealth#11]
If relman has minused an issue from tracking, ie marked a regression as tracking-firefox{version}: -  , then we should exclude those bugs from the release health dashboard. (as they currently are excluded from the Platform triage wiki queries)     This way, we have at least one way to exclude minor regressions and edge cases from what we need to pay attention to.

**Comment by lmandel** [comment]
The point of the query is to ensure that we've made a decision about each bug. I think we indicate the decision in this case by changing the status flag to unaffected, wontfix, or disabled. Flagging based on tracking seems like mixing two different systems with different purposes.

**Comment by lmandel** [comment]
Spoke with Liz and confirmed that we can follow the model that I outlined above.
