### ISSUE TITLE
Edit the GH repo to point to the live site

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/releasehealth#13]
Github supports a URL in the repo metadata and it would be nice if it pointed to https://mozilla.github.io/releasehealth/ to flip back and forth from the code to the live site.

<img width="1009" alt="screen shot 2016-04-09 at 1 15 50 pm" src="https://cloud.githubusercontent.com/assets/601139/14406190/3fbe851e-fe55-11e5-84ae-5b5e2cc829a5.png">

**Comment by lmandel** [comment]
Done.
