### ISSUE TITLE
page layout is all wrong for tall, narrow windows

### ISSUE THREAD

**Issue by froydnj** [mozilla/releasehealth#4]
STR:
1. Open http://mozilla.github.io/releasehealth/
2. Resize window to 1280x1440.

Expected results: a pretty dashboard
Actual results: an unreadable mess

![Screenshot from my machine](https://cloud.githubusercontent.com/assets/151096/13621168/5d7b3ae4-e563-11e5-91b2-45deb38f8cda.png).

**Comment by hallvors** [comment]
This also happens on mobile (as in Firefox Android)
@magsout did you do any CSS analysis?

**Comment by pascalchevrel** [comment]
This is fixed (probably by #44 and earlier css fixes).
