### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/releasehealth#43]
https://mozilla.github.io/releasehealth/ is broken because https://product-details.mozilla.org/1.0/firefox_versions.json is not sending CORS headers:

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://product-details.mozilla.org/1.0/firefox_versions.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by kyoshino** [comment]
Probably a regression from [AWS migration](https://bugzilla.mozilla.org/show_bug.cgi?id=1508781).

**Comment by dklawren** [comment]
Seems to be working for me. I do not see any console errors.

**Comment by pascalchevrel** [comment]
We fixed the CORS headers in https://bugzilla.mozilla.org/show_bug.cgi?id=1541800
