### ISSUE TITLE
Firefox logo images are way too high-res, causing wasted network activity & unnecessary downscaling work

### ISSUE THREAD

**Issue by dholbert** [mozilla/releasehealth#5]
STR:
 1. Visit https://mozilla.github.io/releasehealth/
 2. Right-click the Firefox logo in upper-left corner.
 3. Choose "View Image"

ACTUAL RESULTS:
I'm taken to...
  https://mozilla.github.io/releasehealth/images/firefox-beta.png
...which is higher resolution than my monitor (2485 x 2340 pixels).

EXPECTED RESULTS:
Image should be an order of magnitude smaller, so that it's closer to the right size that it ends up on-screen, and so it can be downscaled (if needed) more efficiently.

(The `<picture>` element might help here, too, if we want to be really fancy and provide different images for different resolutions.)

This manifests in the real world as the image having a noticeable delay before it displays on first pageload, as well as on tab-switch.

**Comment by lmandel** [comment]
This was on my cleanup list. Very noticeable delay loading because of the image size. For now I'm just reducing the image sizes. The approach is not optimal but will be much better than currently.
