### ISSUE TITLE
Add a FIXED BUGS count on skyline view

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/releasehealth#54]
Discussed with the relman team today, we'd like to have a 'Fixed bugs' for the skyline view added to show progress.

**Comment by emceeaich** [comment]
What's the best way to approach this? Should we set it up as an optional column? 

I talked, briefly, with elan yesterday who hope we'd have more displays like this at the program level.

**Comment by pascalchevrel** [comment]
I don't think it needs to be an optional column, there is enough space for 4 values on that view. We can add more projects like skyline, that's easy to do.
