### ISSUE TITLE
Info gets stale, automatic refresh? 

### ISSUE THREAD

**Issue by bagder** [mozilla/releasehealth#9]
Hey, if I leave this open in a tab, the information in it has gone stale after a while and is no longer accurate. To fix that I can of course reload the page. It would work much better as a "always up on screen" sort of page if it would refresh itself, possibly even more smarter than just at a fixed interval.

**Comment by lmandel** [comment]
A simple page refresh or query refresh is easy to implement.
Do you have a suggestion for how you'd like to see the refresh happen if not at a fixed interval?

**Comment by bagder** [comment]
I think it would be nice if the refresh could be done without showing the question marks that get shown again when I manually press reload, but I really don't have any particular insights or good ideas otherwise.
